// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaXLPshWtTtMr7gVihERsnBcWqh30aoS0',
    appId: '1:569961050796:web:eede68f2090467ac0ea509',
    messagingSenderId: '569961050796',
    projectId: 'chadifooddelivery',
    authDomain: 'chadifooddelivery.firebaseapp.com',
    storageBucket: 'chadifooddelivery.appspot.com',
    measurementId: 'G-6C8Q7D0JGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPZGY1-ZnvUjkTAhFR_3pR_oKiJ-kWCTg',
    appId: '1:569961050796:android:41a6225426d7cc710ea509',
    messagingSenderId: '569961050796',
    projectId: 'chadifooddelivery',
    storageBucket: 'chadifooddelivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-SoJzahbXWzTDDs_vWkWjGvob5YB9CM',
    appId: '1:569961050796:ios:12da0bfff038b3630ea509',
    messagingSenderId: '569961050796',
    projectId: 'chadifooddelivery',
    storageBucket: 'chadifooddelivery.appspot.com',
    iosBundleId: 'com.example.restau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-SoJzahbXWzTDDs_vWkWjGvob5YB9CM',
    appId: '1:569961050796:ios:12da0bfff038b3630ea509',
    messagingSenderId: '569961050796',
    projectId: 'chadifooddelivery',
    storageBucket: 'chadifooddelivery.appspot.com',
    iosBundleId: 'com.example.restau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaXLPshWtTtMr7gVihERsnBcWqh30aoS0',
    appId: '1:569961050796:web:185770bac7ba5bb70ea509',
    messagingSenderId: '569961050796',
    projectId: 'chadifooddelivery',
    authDomain: 'chadifooddelivery.firebaseapp.com',
    storageBucket: 'chadifooddelivery.appspot.com',
    measurementId: 'G-VRYLGSR7HM',
  );
}
